-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgzKsiLASJ2qVK3gue
+2IwXS9SPoeUhqBu7LSkJHFkE8SgCgYIKoZIzj0DAQehRANCAATLnDjaImVFtP7k
HcHPLMAn97NSdSsylqLlVGUXqx1VFB1NmPcf7WfgxPMprTXa4nOY9cKIMEpMtVzT
wTJF6P88
-----END PRIVATE KEY-----